"""Initial schema

Revision ID: 044ad2e98cd8
Revises: 
Create Date: 2025-06-09 02:55:35.633151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044ad2e98cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sound_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('sound_level', sa.Float(), nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Chatsolution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dog',
    sa.Column('dog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F'), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_table('Device',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['Dog.dog_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('Meal',
    sa.Column('meal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('meal_datetime', sa.DateTime(), nullable=False),
    sa.Column('meal_amount', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['Dog.dog_id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('SoundAnalysis',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.Column('anxiety_level', sa.Integer(), nullable=True),
    sa.Column('sound_features', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['Dog.dog_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('WalkRecord',
    sa.Column('walk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('walk_distance', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('walk_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['Dog.dog_id'], ),
    sa.PrimaryKeyConstraint('walk_id')
    )
    op.create_table('WeightRecord',
    sa.Column('weight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['Dog.dog_id'], ),
    sa.PrimaryKeyConstraint('weight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WeightRecord')
    op.drop_table('WalkRecord')
    op.drop_table('SoundAnalysis')
    op.drop_table('Meal')
    op.drop_table('Device')
    op.drop_table('Dog')
    op.drop_table('Chatsolution')
    op.drop_table('sound_alert')
    op.drop_table('User')
    # ### end Alembic commands ###
