/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AuthGate`; params?: Router.UnknownInputParams; } | { pathname: `/auth_agreement`; params?: Router.UnknownInputParams; } | { pathname: `/auth_login`; params?: Router.UnknownInputParams; } | { pathname: `/auth_main`; params?: Router.UnknownInputParams; } | { pathname: `/auth_register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/option_device`; params?: Router.UnknownInputParams; } | { pathname: `/pet_add`; params?: Router.UnknownInputParams; } | { pathname: `/pet_camera`; params?: Router.UnknownInputParams; } | { pathname: `/pet_modify`; params?: Router.UnknownInputParams; } | { pathname: `/pet_walk`; params?: Router.UnknownInputParams; } | { pathname: `/pet_weight`; params?: Router.UnknownInputParams; } | { pathname: `/test_expovideo`; params?: Router.UnknownInputParams; } | { pathname: `/test_m3u8`; params?: Router.UnknownInputParams; } | { pathname: `/test_mic`; params?: Router.UnknownInputParams; } | { pathname: `/test_video`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chart_chart` | `/chart_chart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main_home` | `/main_home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/option_option` | `/option_option`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AuthGate`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_agreement`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_main`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_register`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/option_device`; params?: Router.UnknownOutputParams; } | { pathname: `/pet_add`; params?: Router.UnknownOutputParams; } | { pathname: `/pet_camera`; params?: Router.UnknownOutputParams; } | { pathname: `/pet_modify`; params?: Router.UnknownOutputParams; } | { pathname: `/pet_walk`; params?: Router.UnknownOutputParams; } | { pathname: `/pet_weight`; params?: Router.UnknownOutputParams; } | { pathname: `/test_expovideo`; params?: Router.UnknownOutputParams; } | { pathname: `/test_m3u8`; params?: Router.UnknownOutputParams; } | { pathname: `/test_mic`; params?: Router.UnknownOutputParams; } | { pathname: `/test_video`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chart_chart` | `/chart_chart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/main_home` | `/main_home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/option_option` | `/option_option`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AuthGate${`?${string}` | `#${string}` | ''}` | `/auth_agreement${`?${string}` | `#${string}` | ''}` | `/auth_login${`?${string}` | `#${string}` | ''}` | `/auth_main${`?${string}` | `#${string}` | ''}` | `/auth_register${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/option_device${`?${string}` | `#${string}` | ''}` | `/pet_add${`?${string}` | `#${string}` | ''}` | `/pet_camera${`?${string}` | `#${string}` | ''}` | `/pet_modify${`?${string}` | `#${string}` | ''}` | `/pet_walk${`?${string}` | `#${string}` | ''}` | `/pet_weight${`?${string}` | `#${string}` | ''}` | `/test_expovideo${`?${string}` | `#${string}` | ''}` | `/test_m3u8${`?${string}` | `#${string}` | ''}` | `/test_mic${`?${string}` | `#${string}` | ''}` | `/test_video${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chart_chart${`?${string}` | `#${string}` | ''}` | `/chart_chart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/main_home${`?${string}` | `#${string}` | ''}` | `/main_home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/option_option${`?${string}` | `#${string}` | ''}` | `/option_option${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AuthGate`; params?: Router.UnknownInputParams; } | { pathname: `/auth_agreement`; params?: Router.UnknownInputParams; } | { pathname: `/auth_login`; params?: Router.UnknownInputParams; } | { pathname: `/auth_main`; params?: Router.UnknownInputParams; } | { pathname: `/auth_register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/option_device`; params?: Router.UnknownInputParams; } | { pathname: `/pet_add`; params?: Router.UnknownInputParams; } | { pathname: `/pet_camera`; params?: Router.UnknownInputParams; } | { pathname: `/pet_modify`; params?: Router.UnknownInputParams; } | { pathname: `/pet_walk`; params?: Router.UnknownInputParams; } | { pathname: `/pet_weight`; params?: Router.UnknownInputParams; } | { pathname: `/test_expovideo`; params?: Router.UnknownInputParams; } | { pathname: `/test_m3u8`; params?: Router.UnknownInputParams; } | { pathname: `/test_mic`; params?: Router.UnknownInputParams; } | { pathname: `/test_video`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chart_chart` | `/chart_chart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main_home` | `/main_home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/option_option` | `/option_option`; params?: Router.UnknownInputParams; };
    }
  }
}
